<?php

namespace Argidomin\HotelBundle\Entity\Ventas;

use Doctrine\ORM\EntityRepository;

/**
 * ComprasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprasRepository extends EntityRepository
{
}
