<?php

namespace Argidomin\HotelBundle\Entity\Ventas;

use Doctrine\ORM\EntityRepository;

/**
 * ReservasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservasRepository extends EntityRepository
{
}
